---
language: python
sudo: required
dist: trusty
cache:
  directories: [ '$HOME/lxc' ]
  pip: true
env:
- LXC_DISTRO=debian LXC_RELEASE=jessie ES_MAJOR=2 ES_MINOR=4
- LXC_DISTRO=ubuntu LXC_RELEASE=xenial ES_MAJOR=2 ES_MINOR=4
- LXC_DISTRO=debian LXC_RELEASE=jessie ES_MAJOR=5 ES_MINOR=0
- LXC_DISTRO=ubuntu LXC_RELEASE=xenial ES_MAJOR=5 ES_MINOR=0
before_cache:
- sudo mkdir $HOME/lxc && sudo tar cf $HOME/lxc/cache.tar /var/cache/lxc/ && sudo chown $USER. $HOME/lxc/cache.tar
install:
- sudo tar xf $HOME/lxc/cache.tar -C / || true
- sudo apt-get install -y expect-dev
- pip install ansible
- ansible --version
- printf '[defaults]\nroles_path=../\nhost_key_checking=False\ncallback_whitelist=profile_tasks'
  >ansible.cfg
- ansible-galaxy install williamyeh.oracle-java lae.travis-lxc
- ansible-playbook -vv tests/install.yml
script:
- ansible-playbook tests/test.yml -i tests/inventory --syntax-check
- ansible-playbook tests/test.yml -i tests/inventory
- unbuffer ansible-playbook tests/test.yml -i tests/inventory --skip dependency >/tmp/idempotency.log 2>&1
- 'grep -A1 "PLAY RECAP" /tmp/idempotency.log | grep -qP "changed=0.*failed=0" &&
  (echo "Idempotence: PASS"; exit 0) || (echo "Idempotence: FAIL"; cat /tmp/idempotency.log;
  exit 1)'
- sudo lxc-attach -n test01 -v PAGER=cat -- journalctl -xn
- ansible -i tests/inventory all -u root -m service -a "name=elasticsearch state=started" -s && sleep 20
- curl http://test01.lxc:9200/
- sudo lxc-attach -n test01 -v PAGER=cat -- journalctl -xu elasticsearch.service
- sudo lxc-attach -n test01 -v PAGER=cat -- /bin/bash -c "cat /var/log/elasticsearch/*"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: UJQvEXSj1m0U/fExnUiThV7TBX8fysJZ8X1QOq2HzEJO35SvK5V/2lgTy/QNqKcAoWPPuh9+81CzRV27cyO8W4sY+Op0Ld29rmoDy3A2yo9UHk7B4H7Q7y2ELGNvIiQZ47gXSWeeRdDE4hHxaE/MHpLItUhw6omSmOf1X+nF/6PAZECQuIcaBGjdI0NMIqF/+SULJ8U/RVKP9jLYOUNM0qP9wgmXaCxw8iCwZlsnYWeXVCSS7pCUG7PTMuOior7VPQL78yG+s4M6fdX8cmrRrl2p2TTqJM+u5yHtDyRKZ01wuD8gTmoMzDlPgaobNb3JBbYAwGVmN9h80iuPqAovh3hxXgkMnNWUEamq6+AppM73y/kzOKSS4+1SIgKOkIQvqSW1BsgUH8XbQXgaylz2pMpnooPk5L/Hp2GF832yBz3xF/oCo3R/ySY3EfZLMte7pDvrBOZFDbCtluxGWNOHzBMXKUW+MjJEtpz9GEvcvhVxJyVD4hOFdrVPCODlScAKNCF2oO917oRj0H2g9Bups6SMYMHwBMt6gVb1L/1NJP4f3r5FjzfVL1g1LmRMd3PvUIBihyDUnPpksBazCgNKZi+6dJd8yFBowi983VthSLAzysmzAAFK9GzqIT3Yv1QURvc1JHH/PSEo36vNzNVFEaVSu9VojPzplMExs+XJuwQ=
