---
language: python
python: '2.7'
sudo: required
dist: trusty
addons:
  apt:
    sources:
    - sourceline: ppa:ubuntu-lxc/stable
    packages:
    - python-pip
    - lxc
    - lxc-templates
    - yum
    - expect-dev
cache:
  directories:
  - "$HOME/lxc/"
  pip: true
before_cache:
- mkdir $HOME/lxc
- sudo tar cf $HOME/lxc/cache.tar /var/cache/lxc/
- sudo chown $USER. $HOME/lxc/cache.tar
env:
  - LXC_NAME=test-debian8 LXC_DISTRO=debian LXC_RELEASE=jessie
install:
- pip install ansible
- ansible --version
- printf '[defaults]\nroles_path=../\nhost_key_checking=False\ncallback_whitelist=profile_tasks'
  >ansible.cfg
- ansible-galaxy install williamyeh.oracle-java
- sudo tar xf $HOME/lxc/cache.tar -C / || echo "Didn't extract cache."
- export LXC_ROOTFS=/var/lib/lxc/$LXC_NAME/rootfs
- '[ "x${LXC_DISTRO}" == "xdebian" ] && sudo LANG= LC_ALL= LC_CTYPE= lxc-create -n
  $LXC_NAME -t debian -- -r $LXC_RELEASE --mirror http://mirrors.us.kernel.org/debian
  --packages python,ca-certificates,curl,sudo || true'
- '[ "x${LXC_DISTRO}" == "xcentos" ] && sudo root_expire_password=no lxc-create -n
  $LXC_NAME -t centos -- -R $LXC_RELEASE || true'
- '[ "x${LXC_DISTRO}" == "xubuntu" ] && sudo lxc-create -n $LXC_NAME -t ubuntu --
  -r $LXC_RELEASE --mirror http://mirrors.us.kernel.org/ubuntu --packages python,ca-certificates,curl,sudo
  || true'
- printf "\nlxc.mount.auto = proc:rw sys:rw cgroup-full:rw\nlxc.aa_profile = unconfined" | sudo tee -a /var/lib/lxc/$LXC_NAME/config
- sudo lxc-start -n $LXC_NAME && until (sudo lxc-info -n $LXC_NAME | grep -q ^IP:);
  do printf . && sleep 1; done && sleep 2
- '[ "x${LXC_DISTRO}" == "xcentos" ] && sudo lxc-attach -n $LXC_NAME -- yum install
    -y epel-release,ca-certificates,sudo || true'
- sudo /bin/bash -c "printf '\n$(sudo lxc-info -Hin $LXC_NAME) test.lxc' >> /etc/hosts"
- ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''
- sudo mkdir -vm 0700 $LXC_ROOTFS/root/.ssh/
- sudo cp -v ~/.ssh/id_rsa.pub $LXC_ROOTFS/root/.ssh/authorized_keys
script:
- ansible-playbook tests/test.yml -i tests/inventory --syntax-check
- ansible-playbook tests/test.yml -i tests/inventory
- unbuffer ansible-playbook tests/test.yml -i tests/inventory --skip dependency >/tmp/idempotency.log
  2>&1
- 'grep -A1 "PLAY RECAP" /tmp/idempotency.log | grep -qP "changed=0.*failed=0" && (echo "Idempotence:
  PASS"; exit 0) || (echo "Idempotence: FAIL"; cat /tmp/idempotency.log; exit 1)'
- ansible -i tests/inventory all -u root -m service -a "name=elasticsearch state=started" -s && sleep 10
- curl http://test.lxc:9200/
- sudo lxc-attach -n $LXC_NAME -v PAGER=cat -- journalctl -xu elasticsearch.service
- sudo cat $LXC_ROOTFS/etc/elasticsearch/elasticsearch.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: UJQvEXSj1m0U/fExnUiThV7TBX8fysJZ8X1QOq2HzEJO35SvK5V/2lgTy/QNqKcAoWPPuh9+81CzRV27cyO8W4sY+Op0Ld29rmoDy3A2yo9UHk7B4H7Q7y2ELGNvIiQZ47gXSWeeRdDE4hHxaE/MHpLItUhw6omSmOf1X+nF/6PAZECQuIcaBGjdI0NMIqF/+SULJ8U/RVKP9jLYOUNM0qP9wgmXaCxw8iCwZlsnYWeXVCSS7pCUG7PTMuOior7VPQL78yG+s4M6fdX8cmrRrl2p2TTqJM+u5yHtDyRKZ01wuD8gTmoMzDlPgaobNb3JBbYAwGVmN9h80iuPqAovh3hxXgkMnNWUEamq6+AppM73y/kzOKSS4+1SIgKOkIQvqSW1BsgUH8XbQXgaylz2pMpnooPk5L/Hp2GF832yBz3xF/oCo3R/ySY3EfZLMte7pDvrBOZFDbCtluxGWNOHzBMXKUW+MjJEtpz9GEvcvhVxJyVD4hOFdrVPCODlScAKNCF2oO917oRj0H2g9Bups6SMYMHwBMt6gVb1L/1NJP4f3r5FjzfVL1g1LmRMd3PvUIBihyDUnPpksBazCgNKZi+6dJd8yFBowi983VthSLAzysmzAAFK9GzqIT3Yv1QURvc1JHH/PSEo36vNzNVFEaVSu9VojPzplMExs+XJuwQ=
